

@echo off
set /p "folderName=기본폴더이름지정: "
echo %folderName%

md "ExtendSource"
md "Plugins"
md "Resources"
md "StreamingAssets"
md "TestSource"
md "Resources/%folderName%"
md "Resources/%folderName%/Object3D"
md "Resources/%folderName%/Object3D/Animation"
md "Resources/%folderName%/Object3D/Data3D"
md "Resources/%folderName%/Object3D/Material"
md "Resources/%folderName%/Object3D/Prefab"
md "Resources/%folderName%/Object3D/Texture"
md "Resources/%folderName%/UI"
md "Resources/%folderName%/UI/Material"
md "Resources/%folderName%/UI/Prefab"
md "Resources/%folderName%/UI/Texture"
md "%folderName%"
md "%folderName%/Scene"
md "%folderName%/Scripts"
md "%folderName%/Scripts/Actor"
md "%folderName%/Scripts/Component"
md "%folderName%/Scripts/Core"
md "%folderName%/Scripts/CoreUI"
md "%folderName%/Scripts/Enum"
md "%folderName%/Scripts/GameLogic"
md "%folderName%/Scripts/GUI"
md "%folderName%/Scripts/Manager"
md "%folderName%/Scripts/Map"
md "%folderName%/Scripts/TestSource"
md "%folderName%/Scripts/Editor"
md "%folderName%/Scripts/ServerIO"
md "%folderName%/Scripts/DataStruct"
md "%folderName%/Data3D"
md "%folderName%/Data3D/Prefab"
md "%folderName%/Resource"
md "%folderName%/UI"

pause